---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexa.
--- DateTime: 25/08/2024 14:15
---

local robot = {}

function robot.name()
    return "name"
end
function robot.detect()
    return true, "dirt"
end
function robot.detectUp()
    return true, "dirt"
end
function robot.detectDown()
    return true, "dirt"
end
function robot.select(slot)
    return slot
end
function robot.inventorySize()
    return 9
end
function robot.count(slot)
    return 32
end
function robot.space(slot)
    return 32
end
function robot.transferTo(slot, count)
    return true
end
function robot.compareTo(slot)
    return true
end
function robot.compare()
    return true
end
function robot.compareUp()
    return true
end
function robot.compareDown()
    return true
end
function robot.drop(count)
    return true
end
function robot.dropUp(count)
    return true
end
function robot.dropDown(count)
    return true
end
function robot.suck(count)
    return true
end
function robot.suckUp(count)
    return true
end
function robot.suckDown(count)
    return true
end
function robot.place(side, sneaky)
    return true
end
function robot.placeUp(side, sneaky)
    return true
end
function robot.placeDown(side, sneaky)
    return true
end
function robot.durability()
    return 20, 20, 200
end
function robot.swing(side, sneaky)
    return true
end
function robot.swingUp(side, sneaky)
    return true
end
function robot.swingDown(side, sneaky)
    return true
end
function robot.use(side, sneaky, duration)
    return true
end
function robot.useUp(side, sneaky, duration)
    return true
end
function robot.useDown(side, sneaky, duration)
    return true
end
function robot.forward()
    return true
end
function robot.back()
    return true
end
function robot.up()
    return true
end
function robot.down()
    return true
end
function robot.turnLeft()
    return true
end
function robot.turnRight()
    return true
end
function robot.turnAround()
    return true
end
function robot.tankCount()
    return 1
end
function robot.selectTank(tank)
end
function robot.tankLevel(tank)
    return 32
end
function robot.tankSpace(tank)
    return 32
end
function robot.compareFluidTo(tank)
    return true
end
function robot.transferFluidTo(tank)
    return true
end
function robot.compareFluid()
    return true
end
function robot.compareFluidUp()
    return true
end
function robot.compareFluidDown()
    return true
end
function robot.drain(count)
    return true
end
function robot.drainUp(count)
    return true
end
function robot.drainDown(count)
    return true
end
function robot.fill(count)
    return true
end
function robot.fillUp(count)
    return true
end
function robot.fillDown(count)
    return true
end

return robot