---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexa.
--- DateTime: 14/04/2025 18:49
---

local version = "0.1"
local programName = "Skylight Tester"
local progNameS = "SkyL_Tst"

local skylight = require("skylight")

local running = true

function StopButton()
    running = false
end

function Random()
    return math.random()
end


local inputText = ""

function TextBox(text, enter)
    if string.len(text) > 0 then
        inputText = inputText .. text    
    end
    
    return inputText
end

local button1Pressed = false
function Button1()
    button1Pressed = not button1Pressed
end

function ButtonState()
    return tostring(button1Pressed)
end

function CreateSkylight()
    skylight.New(programName .. " V" .. version)
    
    skylight.Log(progNameS, "Hello World")
    
    skylight.CreateLabel("Test1")
    skylight.CreateLabel("Test2", true)
    skylight.CreateLabel("Test3")
    skylight.CreateDynamicText("Dynamic: ", Random)
    skylight.CreateProgressBar("Bar1", Random)

    skylight.Log(progNameS, "Sup?")
    
    skylight.CreateProgressBar("Bar2", (function() return 0.1 end), true)
    skylight.CreateProgressBar("Bar2", (function() return 0.6 end), true)
    skylight.CreateTextBox("Text Input",TextBox)
    skylight.CreateDynamicText("Echo: ", (function() return inputText end))
    skylight.CreateButton("Button1", Button1, true)
    skylight.CreateDynamicText("Echo: ", ButtonState)
    skylight.CreateButton("Stop", (function() running = false end))
end

CreateSkylight()

while running do
    skylight.Log(progNameS, "Hi")
    skylight.Draw()
    os.sleep(1)
end 